### ISSUE TITLE
Не добавляется в rails-assets.org

### ISSUE THREAD

**Issue by MaksimPW** [antirek/pixi-editor#1]
Хотел бы использовать ваш редактор
В репозитории pixi-editor (в самом git) не указана версия.
Из-за этого rails-assets не добавляет его.
Можете исправить данную проблему?

**Comment by antirek** [comment]
Не понял, поясните, пожалуйста, немного: в самом git указать версию это как? пометить тегом? Вот так норм: https://github.com/antirek/pixi-editor/releases/tag/v0.0.2 ?

**Comment by MaksimPW** [comment]
Да, именно
Теперь все заработало :+1:
